Adding Chef::Mixin::Command back to Package provider base class
This was removed in #2924, however it breaks at least the yum
provider.

Without this patch, I was getting:
```
    NoMethodError
    -------------
    undefined method `output_of_command' for #<Chef::Provider::Package::Yum:0x00000003a5f278>
```
when trying to execute

```ruby
package "gdb" do
  action :install
end
```

on Centos 6.5

Chef was breaking in weird ways and it didn't produce a stacktrace.out,
which was a little concerning, however that's a different bug